service:
  log_level: info
pipeline:
  inputs:
    - name: tail
      path: /var/log/*.log
      tag: "logs"
  outputs:
    - name: stdout
      match: "*"
      processors:
        metrics:
          - name: labels
            upsert: ostype linux
          - name: labels
            upsert: hostname {{$ .Agent.host_name }}
